index:
    path: /
    controller: App\Controller\HomeController::index

storyboard:
    path: /storyboard
    controller: App\Controller\StoryboardController::index

critaryform:
    path: /critary
    controller: App\Controller\CritaryFormController::new

map_place:
    methods: [GET, POST]
    path: /map
    controller: App\Controller\MapController::newSelectedPlace


