index:
    path: /
    controller: App\Controller\HomeController::index

storyboard:
    path: /storyboard
    controller: App\Controller\StoryboardController::index

critaryform:
    path: /critary
    controller: App\Controller\CritaryFormController::new

map_place:
    methods: [GET, POST]
    path: /map
    controller: App\Controller\MapController::newSelectedPlace

registration:
    path: /registration
    controller: App\Controller\RegistrationController::registration

security_login:
    path: /login
    controller: App\Controller\SecurityController::login

security_logout:
    path: /logout
    controller: App\Controller\SecurityController::logout

confirm_account:
    path: /confirm/{token}
    controller: App\Controller\RegistrationController::confirmAccount

dashboard:
    path: /dashboard
    controller: App\Controller\DashboardController::index

legal_notices:
    path: /legal
    controller: App\Controller\LegalController::legal_notices

terms_services:
    path: /terms_services
    controller: App\Controller\LegalController::terms_services
